all:
	gcc -o Linked_list_example Linked_list_example.c
	gcc -o Time_Dates_example Time_Dates_example.c
	gcc -o Random_Numbers_Example Random_Numbers_example.c
	gcc -o String_Functions_example String_Functions_example.c

run:
	#

clean:
	find . -perm /100 -type f -delete